# Generated by Django 4.2 on 2023-04-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatglobal',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chatonly',
            name='title',
            field=models.TextField(),
        ),
    ]
