# Generated by Django 4.2 on 2023-04-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_chatglobal_title_alter_chatonly_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariya',
            name='userImage',
            field=models.ImageField(null=True, upload_to='images/comentariya'),
        ),
    ]
