# Generated by Django 4.2 on 2023-04-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comentariya_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariya',
            name='userImage',
            field=models.TextField(null=True),
        ),
    ]
