# Generated by Django 4.2 on 2023-04-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_comentariya_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatglobal',
            name='userImage',
            field=models.TextField(null=True),
        ),
    ]
