# Generated by Django 4.2 on 2023-04-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chatglobal_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatonly',
            name='friendImage',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='chatonly',
            name='userImage',
            field=models.TextField(null=True),
        ),
    ]
