# Generated by Django 4.2 on 2023-04-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_chatonly_friendimage_chatonly_userimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatonly',
            name='friendImage',
        ),
    ]
