# Generated by Django 4.2 on 2023-04-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_chatonly_friendimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatonly',
            name='room',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
