# Generated by Django 4.2 on 2023-04-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_chatonly_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatonly',
            name='room',
        ),
        migrations.AlterField(
            model_name='chatonly',
            name='friend',
            field=models.CharField(max_length=250),
        ),
    ]
